- docs/DeveloperGuide.md
Developer Guide has been edited to include more details about the project - CCA Manager.
Add Use Cases, Target user profile, value proposition, and user stories documentation of this project. All of the details are documented until version 1.2. The above information for the remaining features that will be made in later versions will be updated to the Developer Guide later.
> Add Use Cases, Target user profile, value proposition, and user stories documentation

- README.md
Part of https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/6.
TODO: Mockup UI.
> Update README for CCA Manager details

- docs/UserGuide.md
Part of https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/8
> Remove AB3 from user guide

- docs/DeveloperGuide.md
> Update non-functional requirements.

- .github/workflows/gradle.yml
Closes https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/19
> Add codecov CI

- build.gradle
- src/main/java/seedu/address/commons/core/LogsCenter.java
- src/main/resources/view/MainWindow.fxml
Fixes https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/40
> Rename user-facing parts to CCA Manager

- docs/diagrams/BetterModelClassDiagram.puml
- docs/diagrams/ModelClassDiagram.puml
1. BetterModelClassDiagram.puml now allows multiple Cca to be referenced by Person
2. ModelClassDiagram.puml now uses Cca instead of CCA
Fixed #53
> Fixes 2 puml files

- src/main/java/seedu/address/ui/PersonCard.java
- src/main/java/seedu/address/ui/PersonListPanel.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/PersonListCard.fxml
> Implements Role and CCA labels in PersonCard

- docs/diagrams/ModelClassDiagram.puml
Fixes https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/61
> Update UniqueCcaList in model class diagram

- docs/UserGuide.md
It adds too many formatting things that breaks the rendering.
Part of https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/62
> Partially revert 1213e98

- docs/UserGuide.md
Delete the whole original UG and create the temp appendix for now, if more features or ideas come in the future will add to it.
Moreover, for beauty, not sure whether to put the introduction outside or inside the collapsed section. So I didn't write the Intro appendix for now.
The only attribute added is the glossary, copied from the original table.
Merge this into the new branch under the tp, in order to prevent conflict and in the end combine all the updated UG together.
> Update UserGuide.md about Appendix

- docs/UserGuide.md
Closes https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/69
> Explain target audience prerequisite knowledge

- docs/UserGuide.md
> Add an introduction to the UG

- docs/UserGuide.md
Literally can't think of any more. Technical FAQs should be placed under the new `Common Issues` section.
Fixes #67
> Adds FAQ questions in UG

- docs/UserGuide.md
Closes https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/69
> Add small gloassary and os-specific info

- docs/UserGuide.md
- docs/stylesheets/main.css
> Style print navbar in UG

- docs/UserGuide.md
Fixes https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/85
> Update UserGuide.md about wrong command in UG

- docs/DeveloperGuide.md
Part of https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/97
> Update DeveloperGuide with payment splitting

- docs/DeveloperGuide.md
Added proposed implementation for
Attendance Tracking feature.
Part of #97
> Update DG with Attendance Tracking

- docs/DeveloperGuide.md
- docs/diagrams/HalfBetterModelClassDiagram.puml
- docs/diagrams/NewUiClassDiagram.puml
- docs/stylesheets/main.css
> Update Developer Guide with the proposed Better CCA-level Actions Meta-feature

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/AssignCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/OweCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Metadata.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/model/person/MetadataTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Closes #106 
Add metacontact to the CCA manager
> Add metacontact to the CCA manager

- src/main/java/seedu/address/logic/commands/AssignCommand.java
- src/main/java/seedu/address/logic/commands/FilterCommand.java
- src/main/java/seedu/address/logic/parser/AssignCommandParser.java
- src/main/java/seedu/address/logic/parser/FilterCommandParser.java
- src/main/java/seedu/address/model/person/CcaContainsKeywordPredicate.java
- src/test/java/seedu/address/logic/commands/AssignCommandTest.java
- src/test/java/seedu/address/logic/commands/FilterCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
- src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
- src/test/java/seedu/address/model/person/RoleContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/testutil/AssignPersonDescriptorBuilder.java
Fixes https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/112
> Add ability to filer by CCA and roles

- src/main/java/seedu/address/ui/HelpWindow.java
Fixes #121.
Fixes #131 
Fixes #163 
Fixes #164
> Change help URL to CCA Manager

- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/ui/PersonCard.java
> Fix sample data and added text wrap to UI so that I can do the screenshots for UG

- docs/UserGuide.md
Apologies, made a hasty merge so now I need another pull request to fix things.
See [comment](https://github.com/AY2324S2-CS2103T-W11-2/tp/pull/192#issuecomment-2053719800)
> Fix broken link detector

- src/main/java/seedu/address/model/person/Name.java
- src/test/java/seedu/address/model/person/NameTest.java
> Fix Name Accepting Numbers

- docs/UserGuide.md
Still need to add `info`, `warnings` and `tips`.
Looks like this now:
[CCA Manager - User Guide - AddressBook Level-3.pdf](https://github.com/AY2324S2-CS2103T-W11-2/tp/files/14970755/CCA.Manager.-.User.Guide.-.AddressBook.Level-3.pdf)
> Partially filled command formats

- docs/UserGuide.md
- docs/index.md
Part of https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/83.
> Fix links and landing page

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/AssignCommand.java
- src/main/java/seedu/address/logic/commands/ChargeCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCcaCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/FilterCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/SetAttCommand.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
> Removed Ability to Assign Role for Add, Assign and Edit Commands without CCA

- docs/tutorials/AddRemark.md
- src/main/java/seedu/address/model/UserPrefs.java
- src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
- src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
- src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Fixes https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/207
> Rename addressbook.json to ccamanager.json

- src/main/java/seedu/address/logic/commands/DeleteCcaCommand.java
- src/main/java/seedu/address/model/person/Person.java
Fixes https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/211
> Delete roles after deleting CCA

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
> Edit Command Automatically Removes Roles when a CCAs are also removed from a Contact

- docs/UserGuide.md
> Update UG to Reflect Roles not Being Applicable for People without CCA

- docs/DeveloperGuide.md
- src/main/java/seedu/address/model/person/Phone.java
Add some reference for phone validation part
> Add some reference for phone validation part

- docs/DeveloperGuide.md
> Use BigDecimal in devguide

- docs/DeveloperGuide.md
> Fix DG To Say CCA Manager instead of AB3 Addressbook
